### ISSUE TITLE
Learning HTML5

### ISSUE THREAD

**Issue by kim00053** [smcs/online-language-lab#2]
on w3schools

**Comment by battis** [comment]
Specifically, @aigerimbishigayeva and @kim00053 :
1. You need to figure out how to capture a webcam and/or mic feed
2. You would like to have some sort of user interface (Check out [Bootstrap](http://getbootstrap.com)
3. You would like to have a good IDE ([Eclipse](https://marketplace.eclipse.org/category/free-tagging/html5) can do this… but there may be better tools: I hear good things about [Tumult Hype](http://tumult.com/hype/whats-new/3.5/)
4. You probably want to start exploring the client-to-server communication via AJAX or similar technologies (Hype will help with that).

And. most importantly, you want to break these out into separate issues, so you can check them off one at a time!
