### ISSUE TITLE
Choose user interface

### ISSUE THREAD

**Issue by ghost** [smcs/online-language-lab#7]
Like bootstrap - put together html look.

**Comment by battis** [comment]
[A thought](http://www.sitepoint.com/accessible-drag-drop/) for assigning users to groups in the teacher interface.

**Comment by kim00053** [comment]
This will not concern us until the final stage of our project, but I wanted to leave a comment so I don't forget. Google recently introduced this tool called "Resizer", which lets designers view UI from different devices. You can simply google Google Resizer and you will be able to find out more info. Thought this could come handy later and wanted to share! :)
